// Marketplace product data - 50 items from circular building material partners

export interface MarketplaceItem {
    id: string;
    slug: string;
    title: string;
    category: string;
    description: string;
    specs: {
        label: string;
        value: string;
    }[];
    quantity: number;
    unit: string;
    condition: "A" | "B" | "C";
    price: number | null; // null = "op aanvraag"
    location: string;
    distanceKm: number;
    source: string;
    sourceType: "partner" | "open";
    verified: boolean;
    lastUpdated: string;
    availability: "direct" | "op_aanvraag";
    co2SavingKg: number | null; // null = n.v.t.
    imageUrl: string | null;
}

const SOURCES = {
    insertMarktplaats: { name: "Insert Marktplaats", verified: true },
    circulairDepotUtrecht: { name: "Circulair Depot Utrecht", verified: true },
    weurtMaterialen: { name: "Weurt Materialen", verified: false },
    reuseBouwRotterdam: { name: "Reuse Bouw Rotterdam", verified: true },
    groenRecycling: { name: "Groen Recycling Eindhoven", verified: false },
};

const LOCATIONS = [
    { city: "Utrecht", distance: 12 },
    { city: "Amsterdam", distance: 45 },
    { city: "Rotterdam", distance: 67 },
    { city: "Den Haag", distance: 58 },
    { city: "Eindhoven", distance: 95 },
    { city: "Nijmegen", distance: 78 },
    { city: "Arnhem", distance: 82 },
    { city: "Groningen", distance: 185 },
    { city: "Tilburg", distance: 88 },
    { city: "Breda", distance: 92 },
];

// Generate 50 realistic marketplace items
export const marketplaceItems: MarketplaceItem[] = [
    // HOUT - 12 items
    {
        id: "h001",
        slug: "vuren-balk-63x175-4m",
        title: "Vuren balk 63×175 – 4.2m",
        category: "hout",
        description: "Gedroogde vuren balken, geschikt voor constructief hergebruik. Afkomstig van sloopproject kantoorpand.",
        specs: [
            { label: "Afmeting", value: "63 × 175 mm" },
            { label: "Lengte", value: "4.2 m" },
            { label: "Houtsoort", value: "Vuren" },
        ],
        quantity: 42,
        unit: "stuks",
        condition: "B",
        price: 28,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "12 uur geleden",
        availability: "direct",
        co2SavingKg: 45,
        imageUrl: "https://xa5knx407r.cloudimg.io/https://xa5knx407r.cloudimg.io/https://www.sleiderink.nl/media/catalog/product/cache/763206d4bb1e1a7b8f656eb5ed95cc58/v/u/vuren_geschaafd_63x175.jpg",
    },
    {
        id: "h002",
        slug: "eiken-kozijn-180x90",
        title: "Eiken kozijn 180×90cm – compleet",
        category: "hout",
        description: "Massief eiken kozijn met dubbele beglazing. Goed onderhouden, direct herbruikbaar.",
        specs: [
            { label: "Afmeting", value: "180 × 90 cm" },
            { label: "Houtsoort", value: "Eiken" },
            { label: "Beglazing", value: "Dubbel" },
        ],
        quantity: 8,
        unit: "stuks",
        condition: "A",
        price: 185,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 62,
        imageUrl: "https://www.webo.nl/wp-content/uploads/Eiken-Kozijn%C2%AE-transparant-1.png",
    },
    {
        id: "h003",
        slug: "grenen-plank-22x150",
        title: "Grenen planken 22×150 – div. lengtes",
        category: "hout",
        description: "Geschaafde grenen planken, diverse lengtes 2-4m. Geschikt voor interieur en afwerking.",
        specs: [
            { label: "Afmeting", value: "22 × 150 mm" },
            { label: "Lengte", value: "2-4 m" },
            { label: "Houtsoort", value: "Grenen" },
        ],
        quantity: 120,
        unit: "m²",
        condition: "B",
        price: 12,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "6 uur geleden",
        availability: "direct",
        co2SavingKg: 28,
        imageUrl: "https://www.martenshout.be/assets/media/9066/conversions/thermowood-vurengrenen-22-x-150-mm-prod_xl.jpg",
    },
    {
        id: "h004",
        slug: "hardhouten-palen-12x12",
        title: "Hardhouten palen 12×12cm – 3m",
        category: "hout",
        description: "Azobe hardhouten palen, ideaal voor buitentoepassing. Minimale verwering.",
        specs: [
            { label: "Afmeting", value: "120 × 120 mm" },
            { label: "Lengte", value: "3 m" },
            { label: "Houtsoort", value: "Azobe" },
        ],
        quantity: 35,
        unit: "stuks",
        condition: "A",
        price: 75,
        location: "Nijmegen",
        distanceKm: 78,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "4 dagen geleden",
        availability: "direct",
        co2SavingKg: 85,
        imageUrl: "https://www.onlinetuinhout.nl/image/cache/catalog/02019-carp/azobe-ruw-paal-500x500.jpg",
    },
    {
        id: "h005",
        slug: "douglas-gevelbekleding",
        title: "Douglas gevelbekleding – gebrand",
        category: "hout",
        description: "Gebrand douglas hout (Shou Sugi Ban stijl). Unieke uitstraling voor gevels.",
        specs: [
            { label: "Afmeting", value: "18 × 140 mm" },
            { label: "Lengte", value: "2.4 m" },
            { label: "Behandeling", value: "Gebrand" },
        ],
        quantity: 85,
        unit: "m²",
        condition: "A",
        price: 45,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 38,
        imageUrl: "https://vandouglashout.com/cdn/shop/files/Shou-sugi-ban-op-gevel.jpg?v=1759846202",
    },
    {
        id: "h006",
        slug: "beuken-trap-compleet",
        title: "Beuken trap – 14 treden compleet",
        category: "hout",
        description: "Complete beukenhouten trap met leuning. Afkomstig van renovatieproject.",
        specs: [
            { label: "Treden", value: "14 stuks" },
            { label: "Breedte", value: "90 cm" },
            { label: "Houtsoort", value: "Beuken" },
        ],
        quantity: 1,
        unit: "set",
        condition: "B",
        price: 450,
        location: "Den Haag",
        distanceKm: 58,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 120,
        imageUrl: "https://cdn.webshopapp.com/shops/47685/files/438816490/tradi-eco-vaste-trap-recht-beukenhout-80-cm-breed.jpg",
    },
    {
        id: "h007",
        slug: "meranti-kozijnen-set",
        title: "Meranti kozijnen – set van 6",
        category: "hout",
        description: "Set van 6 meranti kozijnen, diverse maten. Geschikt voor renovatie woonhuis.",
        specs: [
            { label: "Aantal", value: "6 stuks" },
            { label: "Houtsoort", value: "Meranti" },
            { label: "Afwerking", value: "Wit gelakt" },
        ],
        quantity: 6,
        unit: "stuks",
        condition: "B",
        price: null,
        location: "Eindhoven",
        distanceKm: 95,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "op_aanvraag",
        co2SavingKg: 95,
        imageUrl: "https://www.dekozijnenman.frl/wp-content/uploads/2021/12/kozijn_f_draai-uitzet.jpg",
    },
    {
        id: "h008",
        slug: "vuren-dakspanten",
        title: "Vuren dakspanten – A-spant",
        category: "hout",
        description: "Complete A-spanten voor dakconstructie. Span circa 8 meter.",
        specs: [
            { label: "Type", value: "A-spant" },
            { label: "Span", value: "8 m" },
            { label: "Houtsoort", value: "Vuren" },
        ],
        quantity: 12,
        unit: "stuks",
        condition: "A",
        price: 320,
        location: "Arnhem",
        distanceKm: 82,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "5 uur geleden",
        availability: "direct",
        co2SavingKg: 185,
        imageUrl: "https://passiefhuismarkt.nl/wp-content/uploads/2019/07/gordingen-spanten.jpg",
    },
    {
        id: "h009",
        slug: "eiken-vloerdelen-massief",
        title: "Eiken vloerdelen massief – 20mm",
        category: "hout",
        description: "Massief eiken vloerdelen, al geschuurd. Klaar voor afwerking.",
        specs: [
            { label: "Dikte", value: "20 mm" },
            { label: "Breedte", value: "180 mm" },
            { label: "Oppervlak", value: "Geschuurd" },
        ],
        quantity: 65,
        unit: "m²",
        condition: "A",
        price: 85,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "8 uur geleden",
        availability: "direct",
        co2SavingKg: 52,
        imageUrl: "https://www.floorsite.nl/wp-content/uploads/2021/01/Massief-eiken-rustiek-24cm-breed-2-300x247.png",
    },
    {
        id: "h010",
        slug: "tuinhout-palen",
        title: "Geïmpregneerde tuinpalen – 9×9cm",
        category: "hout",
        description: "Verduurzaamde tuinpalen, diverse lengtes 2-3m beschikbaar.",
        specs: [
            { label: "Afmeting", value: "90 × 90 mm" },
            { label: "Lengte", value: "2-3 m" },
            { label: "Behandeling", value: "Geïmpregneerd" },
        ],
        quantity: 80,
        unit: "stuks",
        condition: "B",
        price: 8,
        location: "Tilburg",
        distanceKm: 88,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 15,
        imageUrl: "https://static.karwei.nl/dam/205760/123",
    },
    {
        id: "h011",
        slug: "underlayment-platen",
        title: "Underlayment platen 18mm",
        category: "hout",
        description: "Underlayment platen in goede staat. Enkele lichte gebruikssporen.",
        specs: [
            { label: "Dikte", value: "18 mm" },
            { label: "Afmeting", value: "244 × 122 cm" },
            { label: "Type", value: "Underlayment" },
        ],
        quantity: 45,
        unit: "platen",
        condition: "B",
        price: 22,
        location: "Utrecht",
        distanceKm: 12,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 18,
        imageUrl: null,
    },
    {
        id: "h012",
        slug: "multiplex-watervast",
        title: "Multiplex watervast 18mm",
        category: "hout",
        description: "Watervaste multiplex platen, geschikt voor buitengebruik.",
        specs: [
            { label: "Dikte", value: "18 mm" },
            { label: "Afmeting", value: "250 × 125 cm" },
            { label: "Kwaliteit", value: "WBP" },
        ],
        quantity: 28,
        unit: "platen",
        condition: "A",
        price: 35,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "4 uur geleden",
        availability: "direct",
        co2SavingKg: 24,
        imageUrl: "https://cdn.webshopapp.com/shops/34832/files/96527162/650x650x2/okoume-watervast-multiplex-blank-18mm-2500x1220mm.jpg",
    },

    // STEEN - 12 items
    {
        id: "s001",
        slug: "baksteen-rood-waalformaat",
        title: "Baksteen rood – Waalformaat",
        category: "steen",
        description: "Klassieke rode baksteen in Waalformaat. Schoongemaakt en palletklaar.",
        specs: [
            { label: "Formaat", value: "Waalformaat" },
            { label: "Kleur", value: "Rood" },
            { label: "Per pallet", value: "500 stuks" },
        ],
        quantity: 12000,
        unit: "stuks",
        condition: "B",
        price: 0.35,
        location: "Nijmegen",
        distanceKm: 78,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 420,
        imageUrl: null,
    },
    {
        id: "s002",
        slug: "betontegels-30x30-grijs",
        title: "Betontegels 30×30 – grijs",
        category: "steen",
        description: "Grijze betontegels, geschikt voor terras of pad. Licht gebruikt.",
        specs: [
            { label: "Afmeting", value: "30 × 30 × 4.5 cm" },
            { label: "Kleur", value: "Grijs" },
            { label: "Gewicht", value: "ca. 10 kg/stuk" },
        ],
        quantity: 850,
        unit: "stuks",
        condition: "B",
        price: 1.5,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "6 uur geleden",
        availability: "direct",
        co2SavingKg: 185,
        imageUrl: null,
    },
    {
        id: "s003",
        slug: "klinkers-gebakken-antraciet",
        title: "Gebakken klinkers antraciet",
        category: "steen",
        description: "Donkere gebakken klinkers, keiformaat. Ideaal voor opritten.",
        specs: [
            { label: "Formaat", value: "Keiformaat" },
            { label: "Kleur", value: "Antraciet" },
            { label: "Dikte", value: "8 cm" },
        ],
        quantity: 4500,
        unit: "stuks",
        condition: "A",
        price: 0.65,
        location: "Eindhoven",
        distanceKm: 95,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "direct",
        co2SavingKg: 320,
        imageUrl: null,
    },
    {
        id: "s004",
        slug: "betonnen-stoeptegels-50x50",
        title: "Betonnen stoeptegels 50×50",
        category: "steen",
        description: "Grote betonnen stoeptegels, geschikt voor terrassen en paden.",
        specs: [
            { label: "Afmeting", value: "50 × 50 × 5 cm" },
            { label: "Kleur", value: "Grijs" },
            { label: "Gewicht", value: "ca. 28 kg/stuk" },
        ],
        quantity: 320,
        unit: "stuks",
        condition: "B",
        price: 4.5,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 145,
        imageUrl: null,
    },
    {
        id: "s005",
        slug: "natuursteen-bluestone",
        title: "Natuursteen Belgisch hardsteen",
        category: "steen",
        description: "Belgisch hardsteen (Bluestone) tegels. Geschikt voor binnen en buiten.",
        specs: [
            { label: "Afmeting", value: "60 × 40 × 3 cm" },
            { label: "Type", value: "Belgisch hardsteen" },
            { label: "Oppervlak", value: "Geschuurd" },
        ],
        quantity: 45,
        unit: "m²",
        condition: "A",
        price: 95,
        location: "Den Haag",
        distanceKm: 58,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 210,
        imageUrl: null,
    },
    {
        id: "s006",
        slug: "muurblokken-kalkzand",
        title: "Kalkzandsteen muurblokken",
        category: "steen",
        description: "Kalkzandsteen blokken voor draagmuren. Schoon en direct inzetbaar.",
        specs: [
            { label: "Afmeting", value: "43.7 × 10 × 29.8 cm" },
            { label: "Type", value: "Kalkzandsteen" },
            { label: "Sterkteklasse", value: "CS 12" },
        ],
        quantity: 2400,
        unit: "stuks",
        condition: "A",
        price: 0.85,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "12 uur geleden",
        availability: "direct",
        co2SavingKg: 580,
        imageUrl: null,
    },
    {
        id: "s007",
        slug: "graniet-randstenen",
        title: "Graniet randstenen",
        category: "steen",
        description: "Granieten randstenen/trottoirbanden. Zeer duurzaam materiaal.",
        specs: [
            { label: "Afmeting", value: "100 × 15 × 25 cm" },
            { label: "Type", value: "Graniet" },
            { label: "Kleur", value: "Grijs/roze" },
        ],
        quantity: 85,
        unit: "strekkende meter",
        condition: "A",
        price: 28,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "5 uur geleden",
        availability: "direct",
        co2SavingKg: 165,
        imageUrl: null,
    },
    {
        id: "s008",
        slug: "dakpannen-beton-rood",
        title: "Betonnen dakpannen rood",
        category: "steen",
        description: "Betonnen dakpannen, model Sneldek. Incidentele breuken al verwijderd.",
        specs: [
            { label: "Type", value: "Sneldek" },
            { label: "Kleur", value: "Rood" },
            { label: "Per m²", value: "ca. 10 stuks" },
        ],
        quantity: 2800,
        unit: "stuks",
        condition: "B",
        price: 0.45,
        location: "Arnhem",
        distanceKm: 82,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "4 dagen geleden",
        availability: "direct",
        co2SavingKg: 380,
        imageUrl: null,
    },
    {
        id: "s009",
        slug: "betonplaten-200x100",
        title: "Betonplaten 200×100×12cm",
        category: "steen",
        description: "Zware betonplaten, geschikt voor industrieterreinen of erfverharding.",
        specs: [
            { label: "Afmeting", value: "200 × 100 × 12 cm" },
            { label: "Gewicht", value: "ca. 600 kg/stuk" },
            { label: "Type", value: "Vlakke plaat" },
        ],
        quantity: 45,
        unit: "stuks",
        condition: "B",
        price: 65,
        location: "Tilburg",
        distanceKm: 88,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "op_aanvraag",
        co2SavingKg: 450,
        imageUrl: null,
    },
    {
        id: "s010",
        slug: "keramische-vloertegels",
        title: "Keramische vloertegels 60×60",
        category: "steen",
        description: "Groot formaat keramische tegels, betonlook. Geschikt voor vloerverwarming.",
        specs: [
            { label: "Afmeting", value: "60 × 60 cm" },
            { label: "Dikte", value: "10 mm" },
            { label: "Look", value: "Beton grijs" },
        ],
        quantity: 52,
        unit: "m²",
        condition: "A",
        price: 18,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 78,
        imageUrl: null,
    },
    {
        id: "s011",
        slug: "waaltjes-gebakken",
        title: "Waaltjes gebakken – mix kleuren",
        category: "steen",
        description: "Authentieke gebakken waaltjes in gemengde kleuren. Karakter voor tuinen.",
        specs: [
            { label: "Formaat", value: "Waalformaat dun" },
            { label: "Kleur", value: "Mix rood/bruin" },
            { label: "Dikte", value: "ca. 3 cm" },
        ],
        quantity: 3200,
        unit: "stuks",
        condition: "B",
        price: 0.55,
        location: "Breda",
        distanceKm: 92,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "5 dagen geleden",
        availability: "direct",
        co2SavingKg: 245,
        imageUrl: null,
    },
    {
        id: "s012",
        slug: "leisteen-dak",
        title: "Leien dakbedekking – Spaans",
        category: "steen",
        description: "Spaanse dakleien, traditioneel formaat. Gedemonteerd van monumentpand.",
        specs: [
            { label: "Formaat", value: "30 × 20 cm" },
            { label: "Herkomst", value: "Spaans" },
            { label: "Dikte", value: "4-6 mm" },
        ],
        quantity: 1800,
        unit: "stuks",
        condition: "A",
        price: 2.8,
        location: "Den Haag",
        distanceKm: 58,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 290,
        imageUrl: null,
    },

    // METAAL - 8 items
    {
        id: "m001",
        slug: "stalen-ipn-balken",
        title: "Stalen IPN balken 180",
        category: "metaal",
        description: "IPN 180 stalen balken, diverse lengtes 4-6m. Gecheckt op roest.",
        specs: [
            { label: "Profiel", value: "IPN 180" },
            { label: "Lengte", value: "4-6 m" },
            { label: "Materiaal", value: "Staal S235" },
        ],
        quantity: 18,
        unit: "stuks",
        condition: "B",
        price: 145,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 520,
        imageUrl: null,
    },
    {
        id: "m002",
        slug: "aluminium-kozijnen-wit",
        title: "Aluminium kozijnen wit",
        category: "metaal",
        description: "Witte aluminium kozijnen met dubbel glas. Diverse maten beschikbaar.",
        specs: [
            { label: "Materiaal", value: "Aluminium" },
            { label: "Kleur", value: "RAL 9016 wit" },
            { label: "Beglazing", value: "HR++" },
        ],
        quantity: 24,
        unit: "stuks",
        condition: "A",
        price: 320,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "8 uur geleden",
        availability: "direct",
        co2SavingKg: 185,
        imageUrl: null,
    },
    {
        id: "m003",
        slug: "stalen-hekwerk-panelen",
        title: "Stalen hekwerk panelen",
        category: "metaal",
        description: "Verzinkte stalen hekwerkpanelen met betonnen voeten beschikbaar.",
        specs: [
            { label: "Afmeting", value: "200 × 120 cm" },
            { label: "Behandeling", value: "Verzinkt" },
            { label: "Maaswijdte", value: "5 × 20 cm" },
        ],
        quantity: 65,
        unit: "panelen",
        condition: "B",
        price: 28,
        location: "Eindhoven",
        distanceKm: 95,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "direct",
        co2SavingKg: 95,
        imageUrl: null,
    },
    {
        id: "m004",
        slug: "koperen-dakgoot",
        title: "Koperen dakgoot – halfrond",
        category: "metaal",
        description: "Halfonde koperen dakgoot, 150mm. Mooie patina, direct herbruikbaar.",
        specs: [
            { label: "Type", value: "Halfrond" },
            { label: "Diameter", value: "150 mm" },
            { label: "Materiaal", value: "Koper" },
        ],
        quantity: 42,
        unit: "strekkende meter",
        condition: "A",
        price: 45,
        location: "Utrecht",
        distanceKm: 12,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 125,
        imageUrl: null,
    },
    {
        id: "m005",
        slug: "stalen-trappen-industrieel",
        title: "Stalen trap industrieel – 14 treden",
        category: "metaal",
        description: "Industriële stalen trap met traanplaat treden. Incl. leuning.",
        specs: [
            { label: "Treden", value: "14 stuks" },
            { label: "Breedte", value: "100 cm" },
            { label: "Type", value: "Traanplaat" },
        ],
        quantity: 2,
        unit: "stuks",
        condition: "B",
        price: 850,
        location: "Nijmegen",
        distanceKm: 78,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "6 uur geleden",
        availability: "direct",
        co2SavingKg: 380,
        imageUrl: null,
    },
    {
        id: "m006",
        slug: "zinken-dakbedekking",
        title: "Zinken dakbedekking – rollen",
        category: "metaal",
        description: "Zinken dakbedekking in rollen, 0.7mm dik. Geschikt voor platte daken.",
        specs: [
            { label: "Dikte", value: "0.7 mm" },
            { label: "Breedte", value: "100 cm" },
            { label: "Materiaal", value: "Zink" },
        ],
        quantity: 180,
        unit: "m²",
        condition: "A",
        price: 22,
        location: "Den Haag",
        distanceKm: 58,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 165,
        imageUrl: null,
    },
    {
        id: "m007",
        slug: "radiator-wit",
        title: "Radiator wit – type 22",
        category: "metaal",
        description: "Witte paneelradiatoren type 22, diverse lengtes. Getest op lekkage.",
        specs: [
            { label: "Type", value: "Paneel 22" },
            { label: "Hoogte", value: "60 cm" },
            { label: "Lengte", value: "80-140 cm" },
        ],
        quantity: 35,
        unit: "stuks",
        condition: "B",
        price: 45,
        location: "Arnhem",
        distanceKm: 82,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "4 dagen geleden",
        availability: "direct",
        co2SavingKg: 28,
        imageUrl: null,
    },
    {
        id: "m008",
        slug: "stalen-ligger-hea",
        title: "Stalen ligger HEA 200",
        category: "metaal",
        description: "HEA 200 stalen liggers, 6 meter. Prima voor overkapping of constructie.",
        specs: [
            { label: "Profiel", value: "HEA 200" },
            { label: "Lengte", value: "6 m" },
            { label: "Materiaal", value: "Staal S235" },
        ],
        quantity: 8,
        unit: "stuks",
        condition: "A",
        price: 285,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "12 uur geleden",
        availability: "direct",
        co2SavingKg: 420,
        imageUrl: null,
    },

    // GLAS - 6 items
    {
        id: "g001",
        slug: "isolatieglas-hr",
        title: "Isolatieglas HR++ – diverse maten",
        category: "glas",
        description: "HR++ isolatieglas uit renovatie. Diverse maten, op voorraad bekijken.",
        specs: [
            { label: "Type", value: "HR++" },
            { label: "Opbouw", value: "4-16-4" },
            { label: "Maten", value: "Divers" },
        ],
        quantity: 85,
        unit: "m²",
        condition: "A",
        price: 55,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 145,
        imageUrl: null,
    },
    {
        id: "g002",
        slug: "glasblokken-helder",
        title: "Glazen bouwstenen helder",
        category: "glas",
        description: "Heldere glazen bouwstenen 19×19×8cm. Voor lichtdoorlatende wanden.",
        specs: [
            { label: "Afmeting", value: "19 × 19 × 8 cm" },
            { label: "Type", value: "Helder" },
            { label: "Per m²", value: "ca. 25 stuks" },
        ],
        quantity: 450,
        unit: "stuks",
        condition: "A",
        price: 4.5,
        location: "Utrecht",
        distanceKm: 12,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 65,
        imageUrl: null,
    },
    {
        id: "g003",
        slug: "spiegelglas-panelen",
        title: "Spiegelglas panelen",
        category: "glas",
        description: "Spiegelpanelen uit fitnessruimte. Geschikt voor wand- of deurtoepassing.",
        specs: [
            { label: "Afmeting", value: "200 × 100 cm" },
            { label: "Dikte", value: "6 mm" },
            { label: "Type", value: "Zilverspiegel" },
        ],
        quantity: 12,
        unit: "panelen",
        condition: "A",
        price: 85,
        location: "Den Haag",
        distanceKm: 58,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "5 uur geleden",
        availability: "direct",
        co2SavingKg: 42,
        imageUrl: null,
    },
    {
        id: "g004",
        slug: "draadglas-industrieel",
        title: "Draadglas industrieel",
        category: "glas",
        description: "Industrieel draadglas, brandwerend. Geschikt voor scheidingswanden.",
        specs: [
            { label: "Type", value: "Draadglas" },
            { label: "Dikte", value: "7 mm" },
            { label: "Eigenschap", value: "Brandwerend" },
        ],
        quantity: 28,
        unit: "m²",
        condition: "B",
        price: 35,
        location: "Eindhoven",
        distanceKm: 95,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "op_aanvraag",
        co2SavingKg: 38,
        imageUrl: null,
    },
    {
        id: "g005",
        slug: "gehard-veiligheidsglas",
        title: "Gehard veiligheidsglas 10mm",
        category: "glas",
        description: "Gehard veiligheidsglas, diverse afmetingen beschikbaar op aanvraag.",
        specs: [
            { label: "Dikte", value: "10 mm" },
            { label: "Type", value: "Gehard ESG" },
            { label: "Maten", value: "Op aanvraag" },
        ],
        quantity: 32,
        unit: "m²",
        condition: "A",
        price: 75,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 85,
        imageUrl: null,
    },
    {
        id: "g006",
        slug: "glas-in-lood-raam",
        title: "Glas-in-lood raam – antiek",
        category: "glas",
        description: "Authentiek glas-in-lood raam, art deco patroon. Uit monumentaal pand.",
        specs: [
            { label: "Afmeting", value: "120 × 80 cm" },
            { label: "Stijl", value: "Art Deco" },
            { label: "Periode", value: "ca. 1930" },
        ],
        quantity: 4,
        unit: "stuks",
        condition: "A",
        price: 450,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "4 dagen geleden",
        availability: "direct",
        co2SavingKg: 25,
        imageUrl: null,
    },

    // INSTALLATIE - 6 items
    {
        id: "i001",
        slug: "cv-ketel-intergas",
        title: "CV-ketel Intergas Kombi Kompakt",
        category: "installatie",
        description: "Intergas Kombi Kompakt HRE 36/30, 2019 model. Gereviseerd en getest.",
        specs: [
            { label: "Merk", value: "Intergas" },
            { label: "Type", value: "Kombi Kompakt HRE" },
            { label: "Bouwjaar", value: "2019" },
        ],
        quantity: 3,
        unit: "stuks",
        condition: "A",
        price: 650,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 185,
        imageUrl: null,
    },
    {
        id: "i002",
        slug: "ventilatie-unit-wtw",
        title: "WTW-unit Brink Renovent",
        category: "installatie",
        description: "Brink Renovent HR warmteterugwinunit met filters. Functioneert perfect.",
        specs: [
            { label: "Merk", value: "Brink" },
            { label: "Type", value: "Renovent HR" },
            { label: "Capaciteit", value: "325 m³/h" },
        ],
        quantity: 2,
        unit: "stuks",
        condition: "A",
        price: 425,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "6 uur geleden",
        availability: "direct",
        co2SavingKg: 95,
        imageUrl: null,
    },
    {
        id: "i003",
        slug: "airco-split-unit",
        title: "Airco split-unit Daikin",
        category: "installatie",
        description: "Daikin split-unit airco, koelen en verwarmen. Met nieuwe afstandsbediening.",
        specs: [
            { label: "Merk", value: "Daikin" },
            { label: "Capaciteit", value: "3.5 kW" },
            { label: "Type", value: "Split inverter" },
        ],
        quantity: 5,
        unit: "sets",
        condition: "B",
        price: 380,
        location: "Den Haag",
        distanceKm: 58,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 75,
        imageUrl: null,
    },
    {
        id: "i004",
        slug: "boiler-80-liter",
        title: "Boiler 80 liter – Itho Daalderop",
        category: "installatie",
        description: "Elektrische boiler 80 liter, minder dan 5 jaar oud. Nacontroleerd.",
        specs: [
            { label: "Merk", value: "Itho Daalderop" },
            { label: "Inhoud", value: "80 liter" },
            { label: "Aansluiting", value: "230V" },
        ],
        quantity: 4,
        unit: "stuks",
        condition: "B",
        price: 145,
        location: "Nijmegen",
        distanceKm: 78,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "5 dagen geleden",
        availability: "direct",
        co2SavingKg: 45,
        imageUrl: null,
    },
    {
        id: "i005",
        slug: "zonnepanelen-mono",
        title: "Zonnepanelen mono 300Wp",
        category: "installatie",
        description: "Monokristalijne zonnepanelen 300Wp per stuk. Uit groot project, goed werkend.",
        specs: [
            { label: "Vermogen", value: "300 Wp" },
            { label: "Type", value: "Monokristal" },
            { label: "Afmeting", value: "165 × 99 cm" },
        ],
        quantity: 48,
        unit: "panelen",
        condition: "B",
        price: 55,
        location: "Arnhem",
        distanceKm: 82,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "3 dagen geleden",
        availability: "direct",
        co2SavingKg: 320,
        imageUrl: null,
    },
    {
        id: "i006",
        slug: "warmtepomp-lucht-water",
        title: "Warmtepomp lucht-water – Mitsubishi",
        category: "installatie",
        description: "Mitsubishi Ecodan lucht-water warmtepomp 8kW. Inclusief binnenunit.",
        specs: [
            { label: "Merk", value: "Mitsubishi" },
            { label: "Capaciteit", value: "8 kW" },
            { label: "Type", value: "Lucht-water" },
        ],
        quantity: 1,
        unit: "set",
        condition: "A",
        price: null,
        location: "Tilburg",
        distanceKm: 88,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "1 week geleden",
        availability: "op_aanvraag",
        co2SavingKg: 450,
        imageUrl: null,
    },

    // AFBOUW - 6 items
    {
        id: "a001",
        slug: "binnendeur-stompe-opdek",
        title: "Binnendeur stompe opdek – wit",
        category: "afbouw",
        description: "Witte stompe opdekdeur, standaardmaat 201,5 x 83 cm. Met kozijn.",
        specs: [
            { label: "Afmeting", value: "201.5 × 83 cm" },
            { label: "Type", value: "Stompe opdek" },
            { label: "Kleur", value: "Wit" },
        ],
        quantity: 18,
        unit: "stuks",
        condition: "B",
        price: 65,
        location: "Utrecht",
        distanceKm: 12,
        source: "Circulair Depot Utrecht",
        sourceType: "partner",
        verified: true,
        lastUpdated: "12 uur geleden",
        availability: "direct",
        co2SavingKg: 28,
        imageUrl: null,
    },
    {
        id: "a002",
        slug: "keukenblok-compleet",
        title: "Keukenblok 3m – wit hoogglans",
        category: "afbouw",
        description: "Complete keuken 3 meter, wit hoogglans. Met spoelbak, geen apparatuur.",
        specs: [
            { label: "Lengte", value: "3 m" },
            { label: "Afwerking", value: "Hoogglans wit" },
            { label: "Incl.", value: "Spoelbak + kraan" },
        ],
        quantity: 2,
        unit: "sets",
        condition: "B",
        price: 450,
        location: "Amsterdam",
        distanceKm: 45,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "2 dagen geleden",
        availability: "direct",
        co2SavingKg: 185,
        imageUrl: null,
    },
    {
        id: "a003",
        slug: "sanitair-closetcombinatie",
        title: "Closetcombinatie – Villeroy & Boch",
        category: "afbouw",
        description: "Villeroy & Boch wandcloset met softclose zitting. Vrijwel nieuwstaat.",
        specs: [
            { label: "Merk", value: "Villeroy & Boch" },
            { label: "Type", value: "Wandcloset" },
            { label: "Kleur", value: "Wit" },
        ],
        quantity: 6,
        unit: "stuks",
        condition: "A",
        price: 125,
        location: "Den Haag",
        distanceKm: 58,
        source: "Reuse Bouw Rotterdam",
        sourceType: "partner",
        verified: true,
        lastUpdated: "1 dag geleden",
        availability: "direct",
        co2SavingKg: 35,
        imageUrl: null,
    },
    {
        id: "a004",
        slug: "systeemplafond-tegels",
        title: "Systeemplafond tegels 60×60",
        category: "afbouw",
        description: "Minerale systeemplafondtegels, wit. Inclusief T-profielen op aanvraag.",
        specs: [
            { label: "Afmeting", value: "60 × 60 cm" },
            { label: "Type", value: "Mineraal" },
            { label: "Kleur", value: "Wit" },
        ],
        quantity: 420,
        unit: "stuks",
        condition: "B",
        price: 2.5,
        location: "Rotterdam",
        distanceKm: 67,
        source: "Weurt Materialen",
        sourceType: "open",
        verified: false,
        lastUpdated: "4 dagen geleden",
        availability: "direct",
        co2SavingKg: 65,
        imageUrl: null,
    },
    {
        id: "a005",
        slug: "wastafel-dubbel",
        title: "Dubbele wastafel – massief composiet",
        category: "afbouw",
        description: "Dubbele wastafel in wit composiet, 120cm breed. Met onderkast.",
        specs: [
            { label: "Breedte", value: "120 cm" },
            { label: "Materiaal", value: "Composiet" },
            { label: "Incl.", value: "Onderkast" },
        ],
        quantity: 3,
        unit: "sets",
        condition: "A",
        price: 285,
        location: "Eindhoven",
        distanceKm: 95,
        source: "Insert Marktplaats",
        sourceType: "partner",
        verified: true,
        lastUpdated: "8 uur geleden",
        availability: "direct",
        co2SavingKg: 55,
        imageUrl: null,
    },
    {
        id: "a006",
        slug: "laminaat-eiken-decor",
        title: "Laminaat eiken decor – click",
        category: "afbouw",
        description: "Click-laminaat in eiken decor, 8mm dik. Al eerder gelegd maar goed herbruikbaar.",
        specs: [
            { label: "Dikte", value: "8 mm" },
            { label: "Decor", value: "Eiken naturel" },
            { label: "Systeem", value: "Click" },
        ],
        quantity: 85,
        unit: "m²",
        condition: "B",
        price: 8,
        location: "Breda",
        distanceKm: 92,
        source: "Groen Recycling Eindhoven",
        sourceType: "open",
        verified: false,
        lastUpdated: "6 dagen geleden",
        availability: "direct",
        co2SavingKg: 42,
        imageUrl: null,
    },
];

// Helper functions
export const getCategories = () => [
    { value: "all", label: "Alle categorieën" },
    { value: "hout", label: "Hout" },
    { value: "steen", label: "Steen" },
    { value: "metaal", label: "Metaal" },
    { value: "glas", label: "Glas" },
    { value: "installatie", label: "Installaties" },
    { value: "afbouw", label: "Afbouw" },
];

export const getItemBySlug = (slug: string): MarketplaceItem | undefined => {
    return marketplaceItems.find(item => item.slug === slug);
};

export const filterItems = (
    items: MarketplaceItem[],
    filters: {
        search?: string;
        category?: string;
        maxDistance?: number;
        availability?: string;
        condition?: string;
        verifiedOnly?: boolean;
        minCo2Saving?: number;
        sortBy?: string;
    }
): MarketplaceItem[] => {
    let result = [...items];

    if (filters.search) {
        const searchLower = filters.search.toLowerCase();
        result = result.filter(item =>
            item.title.toLowerCase().includes(searchLower) ||
            item.description.toLowerCase().includes(searchLower) ||
            item.category.toLowerCase().includes(searchLower)
        );
    }

    if (filters.category && filters.category !== "all") {
        result = result.filter(item => item.category === filters.category);
    }

    if (filters.maxDistance) {
        const maxDist = filters.maxDistance;
        result = result.filter(item => item.distanceKm <= maxDist);
    }

    if (filters.availability && filters.availability !== "all") {
        result = result.filter(item => item.availability === filters.availability);
    }

    if (filters.condition && filters.condition !== "all") {
        result = result.filter(item => item.condition === filters.condition);
    }

    if (filters.verifiedOnly) {
        result = result.filter(item => item.verified);
    }

    if (filters.minCo2Saving && filters.minCo2Saving > 0) {
        const minSaving = filters.minCo2Saving;
        result = result.filter(item => item.co2SavingKg && item.co2SavingKg >= minSaving);
    }

    // Sort
    switch (filters.sortBy) {
        case "distance":
            result.sort((a, b) => a.distanceKm - b.distanceKm);
            break;
        case "co2":
            result.sort((a, b) => (b.co2SavingKg || 0) - (a.co2SavingKg || 0));
            break;
        case "recent":
            // Sort by lastUpdated (simplified - assumes "X uur/dagen geleden" format)
            result.sort((a, b) => {
                const getHours = (str: string) => {
                    if (str.includes("uur")) return parseInt(str) || 24;
                    if (str.includes("dag")) return (parseInt(str) || 1) * 24;
                    if (str.includes("week")) return (parseInt(str) || 1) * 168;
                    return 999;
                };
                return getHours(a.lastUpdated) - getHours(b.lastUpdated);
            });
            break;
        default:
            // Relevance - verified first, then by match score approximation
            result.sort((a, b) => {
                if (a.verified !== b.verified) return b.verified ? 1 : -1;
                return (b.co2SavingKg || 0) - (a.co2SavingKg || 0);
            });
    }

    return result;
};
